---
version: '3.9'
services:
  tomcat:
    image: tomcat:jre8-alpine
    ports:
      - "8080:8080"
    volumes:
      - data:/usr/local/tomcat/webapps/test
    container_name: tomcat
    depends_on:
      - maven
  maven:
    build: maven
    volumes:
      - data:/data
    container_name: maven
volumes:
  data: