---
version: '3.9'
services:
  tomcat:
    build: tomcat
    ports:
      - "8080:8080"
    volumes:
      - data:/opt/tomcat/webapps
    container_name: tomcat
    depends_on:
      - maven
  maven:
    build: maven
    volumes:
      - data:/data
    container_name: maven
volumes:
  data:
